name: flutter_practice
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  dio: ^5.0.0
  retrofit: ^4.9.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  retrofit_generator: ^10.2.0
  json_serializable: ^6.8.0


dependency_overrides:
  analyzer: ^8.2.0
  dart_style: 3.1.3  


flutter:
  uses-material-design: true
